version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: swift-code-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=swift_codes_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - swift-network

  # Spring Boot Application
  api:
    build: .
    container_name: swift-code-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/swift_codes_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8080:8080"
    volumes:
      - ./Interns_2025_SWIFT_CODES.xlsx:/app/Interns_2025_SWIFT_CODES.xlsx
    networks:
      - swift-network

volumes:
  mysql-data:

networks:
  swift-network:
    driver: bridge